# -*- coding: utf-8 -*-
"""PyPassword.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dYpgeHbNQVYVFFBTyfj80CEwe2Zyv_U
"""

#Password Generator in 10 Lines of Code

import random
import string
print("Strong PyPassword Generator")

all_chars=string.ascii_letters+string.digits+string.punctuation   #Stores all the ASCII characters in a string.

length=int(input("How many characters in your password?"))        #Take input from user about length of password.

generated_chars = random.choices(all_chars, k=length)             #Makes list of randomly generated characters.

password=""                                                       #Initialize using empty string.
for char in generated_chars:
    password+=char                                                #For loop combines the generated characters into a final string.

print("Here is your password", password)